# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          h2jinee
baseurl:        ""
url:            "http://h2jinee.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         h2jinee
  url:          http://h2jinee.github.io/
  email:        wjsgmlwls97@gmail.com
  github:       h2jinee
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/h2jinee/h2jinee.github.io
